### PR TITLE
update practice tools to API 8

### PR DESCRIPTION
**Pull request by CrossJoy**

### CODE REVIEW

**Comment by brostosjoined** [comment]
Are the print statements supposed to ship with the release version of the mod or you used them for debugging and forgot.

**Comment by CrossJoy** [comment]
> Are the print statements supposed to ship with the release version of the mod or you used them for debugging and forgot.

I only edited 1 plugin file and the utilities json. Somehow the others kinda auto generated.

**Comment by brostosjoined** [comment]
Sorry if you didnt get me i mean this https://github.com/bombsquad-community/plugin-manager/blob/ed22b78564ea71beba16733f4fb6f932116f4c58/plugins/utilities/practice_tools.py#L1135

**Comment by CrossJoy** [comment]
> Sorry if you didnt get me i mean this
> 
> https://github.com/bombsquad-community/plugin-manager/blob/ed22b78564ea71beba16733f4fb6f932116f4c58/plugins/utilities/practice_tools.py#L1135
> 
> ```shell
> settings loaded
> 1
> power settings loaded
> 5
> power settings saved
> 2
> power settings saved
> 2
> power settings saved
> 7
> power settings saved
> (8, 1, 0)
> settings saved
> 1
> power settings saved
> (7, 1, 0)
> settings saved
> ```

oh sry, debugging stuff. U want me to remove them?

**Comment by brostosjoined** [comment]
Yeah

**Comment by rikkolovescats** [comment]
@CrossJoy let's add `.history` to .gitignore and also remove the files that got included from the `.history` directory, also squashing your commits'll be nice so that these files do not show up in commit history

**Comment by CrossJoy** [comment]
anything else @rikkolovescats @brostosjoined  ?

**Comment by brostosjoined** [comment]
I think thats all

**Review by rikkolovescats — APPROVED** [review]
thanks a lot!

**Pull request merged**
