### PR TITLE
Updated share replay to v1.3.0

### PR DESCRIPTION
**Pull request by Loup-Garou911XD**

### CODE REVIEW

**Comment by Loup-Garou911XD** [comment]
Can i safely rebase it?

**Comment by Loup-Garou911XD** [comment]
Did i mess up again?

**Comment by Loup-Garou911XD** [comment]
We good now

**Comment by Loup-Garou911XD** [comment]
Why the check failed :(

**Comment by Freaku17** [comment]
> Why the check failed :(

You uploaded file, CI made md5 hash in json file, you edited the file again but md5 hash is still of old file.
Close & Reopen PR so the CI runs again and enters new md5 hash

**Comment by Loup-Garou911XD** [comment]
Oh shiz i think it's the spaces in comments

**Comment by Loup-Garou911XD** [comment]
5 commits not that bad ey?

**Comment by Loup-Garou911XD** [comment]
Gonna open a new pr

**Comment by Loup-Garou911XD** [comment]
E

**Pull request closed without merging**
