### PR TITLE
Add partition function

### PR DESCRIPTION
**Pull request by kingsamurai123**
Added the partition function to 'PluginWindow' class. This function inserts new line breaks, for a specific character offset count. #89

### CODE REVIEW

**Comment by rikkolovescats** [comment]
looks on the right track, does calling `partition()` for plugin description when displaying plugin window not work?

**Comment by kingsamurai123** [comment]
image
This is the output if i use 'partition(self.plugin.info["description"])'.

**Comment by kingsamurai123** [comment]
image
Moving the function into a different function helped fixing the above issue. But not sure if that is recommended or not. What do you think about it?

**Review by rikkolovescats — APPROVED** [review]
LGTM! Moved partition function to a class method and bumped to v0.2.2.

**Comment by rikkolovescats** [comment]
Thanks @kingsamurai123!

**Pull request merged**
