### PR TITLE
Update server_switch, pro_unlocker by Smoothy to Api 8

### PR DESCRIPTION
**Pull request by DhextraS**

### CODE REVIEW

**Comment by DhextraS** [comment]
Does any one Know y its lead to failuire

**Comment by imayushsaini** [comment]
cool , I just runied this PR

**Comment by DhextraS** [comment]
> cool , I just runied this PR

Lol 😅😅

**Comment by imayushsaini** [comment]
we good now

**Comment by DhextraS** [comment]
> we good now
> 

Nyc, thx correcting my mistakes ill look into it.

**Comment by DhextraS** [comment]
Can you also see the pro_unlocker.py

**Comment by rikkolovescats** [comment]
@imayushsaini we can merge this if it looks good enough

**Review by imayushsaini — APPROVED** [review]
looks good to me.

**Pull request merged**
