### PR TITLE
Update and fix practice tools mod

### PR DESCRIPTION
**Pull request by CrossJoy**
- Fix the bug where the ui is stuck if opened on the server side.
- Fix a bug to set the party icon to always be visible for the newer bombsquad version.

### CODE REVIEW

**Review by Freaku17 — APPROVED** [review]
Nice!!

**Comment by Loup-Garou911XD** [comment]
lmao I fixed it and even create a pr but it wasn't merged for some reason

**Comment by Loup-Garou911XD** [comment]
Rikko asked to create a new one but I forgot

**Comment by Loup-Garou911XD** [comment]
@Freaku17 something broke,it says md5 checksum failed during installation in game

**Comment by Loup-Garou911XD** [comment]
Ci was passing right?

**Pull request merged**
