### PR TITLE
Fixed menu theme for deprecated methods

### PR DESCRIPTION
**Pull request by Loup-Garou911XD**

### CODE REVIEW

**Comment by Freaku17** [comment]
Error in new ver:
```
set_main_menu_window() should be passed a 'from_window' value to help ensure proper UI behavior (/storage/emulated/0/Android/data/net.froemling.bombsquad/files/mods/menu_theme.py line 1989).
```

**Comment by Loup-Garou911XD** [comment]
Yeah ik that warning, that's what I mentioned in discord

**Comment by Loup-Garou911XD** [comment]
We can fix that later

**Comment by Freaku17** [comment]
> We can fix that later

Okay, whenever you feel comfortable 👍

**Comment by Loup-Garou911XD** [comment]
Yeah so we can merge

**Comment by Freaku17** [comment]
> Yeah so we can merge

Yes, we can merge after we fix that

**Comment by Loup-Garou911XD** [comment]
> > Yeah so we can merge
> 
> Yes, we can merge after we fix that

its a warning rn so can we do that in a different pr

**Comment by Freaku17** [comment]
This still has a error, but made it easier for you

**Comment by Loup-Garou911XD** [comment]
Closes #213

**Comment by Freaku17** [comment]
@Loup-Garou911XD This still has the following error; I dunno how to fix...
```
  File "/storage/emulated/0/Android/data/net.froemling.bombsquad/files/mods/menu_theme.py", line 1481, in on_transition_in
    MainMenuWindow(transition=None).get_root_widget(), from_window=self._root_widget
                                                                   ^^^^^^^^^^^^^^^^^
AttributeError: 'MainMenuTheme' object has no attribute '_root_widget'
set_main_menu_window() was passed 'from_window' <bauiv1 'container' widget 0xb40000737e03bd00> but existing main-menu-window is None. (/data/data/net.froemling.bombsquad/no_backup/ballistica_files/ba_data/python/bauiv1lib/mainmenu.py line 1077).
```

**Comment by Loup-Garou911XD** [comment]
That's why I asked to fix that in a different commit
So that the plugin could be functional while we fix a warning

**Comment by Loup-Garou911XD** [comment]
Anyways I'll try to fix it today

**Review by Freaku17 — APPROVED** [review]
Works like a charm now 😄

**Pull request merged**
