### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by vishal332008**

### CODE REVIEW

**Comment by rikkolovescats** [comment]
This won't work. This'll show build as passing even if our CI fails. We need to have something that'll show build as passing in green or failing in red depending on whether the last build actually passed or failed.

**Comment by vishal332008** [comment]
I can't find any option where organization/repository is there...

**Comment by rikkolovescats** [comment]
I believe `:user` should work with organizations too. So if it says `:user/:repo` anywhere that could probably be replaced by `bombsquad-community/plugin-manager`. I'm guessing we'll need the "GitHub Workflow" from https://shields.io/category/build.

You can get the workflow names from the files in https://github.com/bombsquad-community/plugin-manager/tree/main/.github/workflows. Open them and they'll have the `name` field in them.

Try creating a new test branch and purposely fail the CI on this test branch by pushing bad commit(s) to make sure the badge reflects the actual status. You'll also need to replace `:branch` with the name of test branch you'll create.

**Comment by vishal332008** [comment]
ummm...
image

**Comment by vishal332008** [comment]
I requested access , it will go to the email of the owner of the organization , check yours and accept if it is from AppVeyor.

**Comment by rikkolovescats** [comment]
AFAIK it shouldn't have anything to do with AppVeyor. You'll have to use "GitHub Workflow Status" from https://shields.io/category/build.

**Pull request closed without merging**
