### PR TITLE
Update gamemode for API 8

### PR DESCRIPTION
**Pull request by Freaku17**

### CODE REVIEW

**Comment by brostosjoined** [comment]
Check your code i dont think its comlete

**Comment by brostosjoined** [comment]
I dont think its working check the code

**Comment by Freaku17** [comment]
> I dont think its working check the code

Checked, it's working. It's just a team/ffa game with only grabbing functionality. I made this as one of my first mods so it was as simple as this.
Since it was already present here before I just decided to update it.

**Review by brostosjoined — APPROVED** [review]
Thanks for updating.

**Pull request merged**
