### PR TITLE
Resize plugin window

### PR DESCRIPTION
**Pull request by kingsamurai123**
I tried to move around as much as I can, but still the buttons were overlapping hence increased the width and height. But still the buttons looked clunky together. So moved the positions. Is this any better? #111 
Result:
image

### CODE REVIEW

**Comment by Loup-Garou911XD** [comment]
It doesn't look good imo.It breaks the symmetrical and clean looking ui

**Comment by Loup-Garou911XD** [comment]
You can increase the height more if there isn't enough room to work with.

**Comment by kingsamurai123** [comment]
Problems with having multiple branches. Pushed a different one. Will push a new one.

**Comment by kingsamurai123** [comment]
Hi Loup, 
can you try now?

**Review by Loup-Garou911XD — APPROVED** [review]
Looks good!

**Pull request merged**
