### PR TITLE
Loups Transparency

### PR DESCRIPTION
**Pull request by brostosjoined**
Now the modules are directly downloaded from official source code repo instead on my repo and all the modifications needed are done openly in the code.

### CODE REVIEW

**Comment by brostosjoined** [comment]
Bug

**Comment by rikkolovescats** [comment]
let's also add md5sum checks for downloads from external sources

**Comment by brostosjoined** [comment]
> let's also add md5sum checks for downloads from external sources

Is it a thing that I need to do or you and could simply give a hint.

**Review by rikkolovescats — APPROVED** [review]
thanks a lot! :balloon:

**Pull request merged**
